### ISSUE TITLE
Add random data into the pass payload

### ISSUE THREAD

**Issue by gilbsgilbs** [covidpass-org/covidpass#17]
Hi,

I'm not an Apple Wallet expert (and not even an Apple user at all), so please correct me if any of my assumptions are incorrect.

This app sends to the back-end a SHA-1 hash of a payload built from the DGC data. I think the use of SHA-1 is acceptable here (and probably a requirement of Apple Wallet anyways 😒). Still, if I'm not mistaken, the payload is deterministic for a given DGC: https://github.com/covidpass-org/covidpass/blob/888c40c9894b803d40c4eef5b3869691465bd6c4/src/pass.js#L98. So this hash could be used by a modified back-end as a unique identifier for a DGC and could be used for instance to determine how many times a given DGC was scanned or if a DGC you had by another mean has already been processed in the past by the back-end. While I don't think it's very bad, I don't think it is intended and IIUC could easily be avoided at minimum cost by adding some randomly generated bits to the pass payload. As a result, it would leak even less info from the DGC to the back-end and provide even more guarantees to the users.

WDYT?

**Comment by SoerenBusse** [comment]
Hi!

Thanks for bringing this up. I totally agree with you that we should add some random data to the generated `pass.json` file to prevent possible tracking in the backend. I can think about three ways to realize this:

1. Add a new `backField` like "CovidPass UUID` and insert a random UUID here. However the user can see this field in their wallet app.
2. Add a random suffix/prefix to the `serialNumber` in addition to the `uvci` coming from the QR-Code. We need to check if this will break anything, but I don't think so.
3. Add some JSON garbage to the `pass.json` like `"_unused": "<SecureRandomString>"`. In this case, we need to check if the Wallet-Apps still accepts the pass.

I think option 2 would be the preferred one, because it has the less side effects and doesn't rely on third party apps to accept a `pass.json` with unknown fields. What do you think?

**Comment by gilbsgilbs** [comment]
Thanks for replying! Can't help you much with the decision here, you know Apple Wallet better than I do. I think each of your proposal fixes the issue. I'd suggest a bare UUID as serial number (without the uvci as suffix/prefix) as the uvci is already included in the payload.
