### ISSUE TITLE
Generate passes with larger QR codes

### ISSUE THREAD

**Issue by marvinsxtr** [covidpass-org/covidpass#3]
There are different types of pass layouts like boarding pass or coupon which may be more suitable to scan a large QR code

**Comment by rursache** [comment]
i would treat this as a high priority. the small qr can break the whole idea of keeping it in wallet if it can’t be easily scanned

**Comment by hauketoenjes** [comment]
Hi, 

we are limited by Apple in the QR-Code size. We would love to make it larger, but the best fitting case for our use-case is `generic` according to the [Apple Docs](https://developer.apple.com/library/archive/documentation/UserExperience/Conceptual/PassKit_PG/Creating.html#//apple_ref/doc/uid/TP40012195-CH4-SW1). 

Potentially, we could use `boardingPass` to maybe get a bigger QR-Code on the pass, but that would be the wrong use-case.

**Comment by rursache** [comment]
well, a simple option on the page could enable `boardingPass` and let the user decide. not being able to scan the qr code makes the whole wallet thing useless 🤷🏻‍♂️

**Comment by hauketoenjes** [comment]
Hi, I just tested out a few combinations of QR-Code and pass types and  there is no way of making a QR-Code larger on any pass type Apple offers (Boarding Passes, etc.)

The only way of displaying it larger is by using the `PKBarcodeFormatAztec` format for the QR Code. The problem with this is, that the scanning apps (like [CovPassCheck](https://github.com/Digitaler-Impfnachweis/covpass-ios)) are not accepting this format. We are forced to use the `PKBarcodeFormatQR` in order for it to be a valid representation of a vaccination certificate. 

So even enabling Boarding Pass generation would not solve this problem. For more information, see the official Apple docs here:  
- [Wallet Developer Guide: Pass Design and Creation](https://developer.apple.com/library/archive/documentation/UserExperience/Conceptual/PassKit_PG/Creating.html)
- [Lower-Level Keys](https://developer.apple.com/library/archive/documentation/UserExperience/Reference/PassKit_Bundle/Chapters/LowerLevel.html)
- [Top-Level Keys](https://developer.apple.com/library/archive/documentation/UserExperience/Reference/PassKit_Bundle/Chapters/TopLevel.html)


Closing this issue because we are not able to solve it with PassKit.
